spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
      default-filters:
        - PrefixPath=/api/v1
      routes:
        - id: shopping_cart
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**

        - id: shopping_store
          uri: lb://shopping-store
          predicates:
            - Path=/shopping-store/**

        - id: warehouse
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**

        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payment/**

        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**

        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
