spring:
  application:
    name: aggregator

kafka:
  bootstrap-servers: localhost:9092
  topics:
    sensor-events: telemetry.sensors.v1
    snapshots: telemetry.snapshots.v1
  consumer:
    group-id: aggregator-group
    enable-auto-commit: false
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: deserializer.SensorEventDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: serializer.AvroSerializer