spring:
  application:
    name: analyzer
  config:
    import: "configserver:"
    cloud:
      config:
        fail-fast: true
        retry:
          use-random-policy: true
          max-interval: 6000
        discovery:
          enabled: true
          serviceId: config-server

  eureka:
    instance:
      hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/